Review view
msosav/Toysnt pull request #26
Opened 2023-09-10 15:44 UTC by cpalacior

Migue, revisa este push que hice para ya hacer el pull de los nuevos cambios de la navbar

2023-09-10 21:30 UTC, msosav requested changes

2023-09-10 21:30 UTC, msosav commented on resources/views/technique/show.blade.php
> +                    <h6 class="card-subtitle">id: {{ $viewData['technique']->getId() }}</h6>
No es relevante el campo Id
```suggestion
                    
```

2023-09-10 21:30 UTC, msosav commented on database/migrations/2023_09_09_021455_create_reviews_table.php
Por qué hay dos campos llamados `technique_id`?

2023-09-10 21:30 UTC, msosav commented on app/Models/Review.php
> +    public function setTechniqueId(string $techniqueId): void
Si es bueno que haya un setId?

2023-09-10 21:30 UTC, msosav commented on app/Models/Review.php
> +     * $this->attributes['updated_at'] - string - contains when the technique was updated
```suggestion
     * $this->attributes['created_at'] - string - contains when the review was created
     * $this->attributes['updated_at'] - string - contains when the review was updated
```

2023-09-12 00:02 UTC, cpalacior commented on database/migrations/2023_09_09_021455_create_reviews_table.php
uno es para crear la columna y la otra para volverla foreign key

2023-09-12 00:04 UTC, cpalacior commented on app/Models/Review.php
> +    public function setTechniqueId(string $techniqueId): void
es para asignarle el technique, no tiene que ver con el id de la review

2023-09-12 00:05 UTC, cpalacior commented
cerremos este pull request, los cambios se los corregí para el siguiente push

2023-09-12 01:59 UTC, merged